Fixes for #35, removed RandomLib refs
zendframework/zend-math pull request #36
Opened 2018-07-09 13:17 UTC by ezimuel

This PR fixes #35, removing the references to RandomLib. We used [paragonie/random_compat](https://github.com/paragonie/random_compat) instead of [ircmaxell/RandomLib](https://github.com/ircmaxell/RandomLib) since zend-math 3.0.0.

2018-07-09 14:02 UTC, ezimuel commented
Fixed the assertEquals for PHPUnit 7.2+ using numeric instead of strings. This changes is related to this issue https://github.com/sebastianbergmann/phpunit/issues/3185.

2018-07-10 15:12 UTC, weierophinney requested changes

2018-07-10 15:12 UTC, weierophinney commented on src/Rand.php
> -    protected static $generator = null;
Since this is marked `protected`, it should stay in, but me marked `@deprecated`, with a note that it is no longer used internally.

2018-07-10 15:12 UTC, weierophinney commented on test/RandTest.php
> +    public static $custom_random_bytes = false;
Use `camelCase` here, please.

2018-07-10 15:12 UTC, weierophinney commented on test/RandTest.php
> +        $this->expectException('Zend\Math\Exception\RuntimeException');
Import this class, and use `::class` notation here, please.

2018-07-10 15:12 UTC, weierophinney commented on test/RandTest.php
> +        $this->expectException('Zend\Math\Exception\DomainException');
Import this class, and use `::class` notation here, please.

2018-07-10 15:12 UTC, weierophinney commented on test/TestAsset/random_bytes.php
> + * @copyright Copyright (c) 2005-2018 Zend Technologies USA Inc. (http://www.zend.com)
This file is introduced this year, so just `2018`.

2018-07-10 15:12 UTC, weierophinney commented on test/TestAsset/random_bytes.php
> +function random_bytes($length)
Document the parameter and return value, please.

2018-07-10 15:12 UTC, weierophinney commented on test/TestAsset/random_bytes.php
> +        throw new \Exception("Random is not supported");
Import the `Exception` class, please.

2018-07-10 16:02 UTC, ezimuel commented
@weierophinney I incorporated all your feedback, thanks!

2018-07-10 18:57 UTC, merged